import mongoose from 'mongoose';

// Schema for the individual scores generated by the AI (FR31)
const AIScoresSchema = new mongoose.Schema({
    clarity: { type: Number, required: true },
    tone: { type: Number, required: true },
    fluency: { type: Number, required: true },
    emotion: { type: Number, required: true },
    speed: { type: Number, required: true },
    noise: { type: Number, required: true },
    overall_ai_score: { type: Number, required: true },
    feedback: { type: String, required: true } // Text feedback
}, { _id: false });

// Schema for the aggregated Community Scores (FR40)
const CommunityScoresSchema = new mongoose.Schema({
    average_clarity: { type: Number, default: 0 },
    average_tone: { type: Number, default: 0 },
    average_engagement: { type: Number, default: 0 },
    average_overall: { type: Number, default: 0 },
    review_count: { type: Number, default: 0 }, // Total number of reviews received
    community_score: { type: Number, default: 0 } // The average score used in the final calculation
}, { _id: false });


// 1. Define the main Submission Schema
const SubmissionSchema = new mongoose.Schema({
    // Primary Key
    submissionId: {
        type: String, 
        required: true,
        unique: true,
    },

    // References
    challengeId: { // Links to the Challenge collection [cite: 235]
        type: mongoose.Schema.Types.ObjectId, 
        ref: 'Challenge',
        required: true
    },
    userId: { // Links to the User collection [cite: 236]
        type: mongoose.Schema.Types.ObjectId, 
        ref: 'User',
        required: true
    },

    // Audio & Status Data
    audio_url: { // Link to the S3/MinIO (or ImageKit) file [cite: 237]
        type: String,
        required: true
    },
    status: {
        type: String,
        enum: ['pending_ai', 'pending_community', 'scored'],
        default: 'pending_ai' 
    },

    // Scoring Data 
    ai_scores: { // Stores the full output from the Python AI service [cite: 238]
        type: AIScoresSchema,
        required: false 
    },
    community_scores: { // Stores the aggregated community ratings [cite: 239]
        type: CommunityScoresSchema,
        required: false 
    },
    final_score: { // The final calculated score (70% AI + 30% Community) [cite: 240, 138]
        type: Number,
        default: 0
    }
}, {
    timestamps: true 
});

// 2. Create and Export the Mongoose Model
const Submission = mongoose.model('Submission', SubmissionSchema);

export default Submission;